### ISSUE TITLE
Install - missing MPSL

### ISSUE THREAD

**Issue by stef204** [ttcdt/mp-5.x#14]
```
% ./config.sh                                                             
Configuring...
Testing if C compiler supports -g -Wall... OK
Looking for MPDM... OK (../mpdm/)
Looking for MPSL... No
```
Am I missing something?
Do I need to clone and install MPSL separately?  Or pass options to `config.sh`?

This is either on `master` or `tag/5.52`.
Linux x86_64.

**Comment by ttcdt** [comment]
8/3/21 0:57, stef204:

> Do I need to clone and install MPSL separately?

Hi. Yes, you have to clone MPSL separately, just like you did with MPDM. 
No installation is needed, config.sh will find it.

**Comment by stef204** [comment]
Thanks, that worked. 

Is there a way to invoke the `ncurses` version under `X`?  Not build only the `ncurses` version by passing a `--without` option but just getting` mp-5` to execute as `ncurses` while under `X`?

IOW, while running `X11`, be able to alternate between the `gtk/qt` version (which comes up by default when executing `mp` under `X`) and the `ncurses` version (which comes up by default while executing `mp` in Linux Console, no `X`?

Maybe a setting in `~/.mp/mpsl`?

**Comment by stef204** [comment]
Thanks, that worked.

**Comment by ttcdt** [comment]
> Thanks, that worked.
> 
> Is there a way to invoke the |ncurses| version under |X|? Not build only 
> the |ncurses| version by passing a |--without| option but just 
> getting|mp-5| to execute as |ncurses| while under |X|?
> 
> IOW, while running |X11|, be able to alternate between the |gtk/qt| 
> version (which comes up by default when executing |mp| under |X|) and 
> the |ncurses| version (which comes up by default while executing |mp| in 
> Linux Console, no |X|?

Running it with the -txt option selects the compiled-in text interface 
instead of the GUI one.
