### ISSUE TITLE
How to change the location of .mp_state.json?

### ISSUE THREAD

**Issue by 3oheicrw** [ttcdt/mp-5.x#18]
On Windows, it's put in `C:\Users\[Username]\Documents`

I don't know why this location was chosen by default but it's very inconvenient and doesn't follow any standard. If the program is Linux it will put this file in `C:\Users\[Username]` or `C:\Users\[Username]\.mp`. If the program is Windows it will put this file in `%AppData%\mp`. The current location doesn't follow any conventions and it seems there is no options to change it from the program's UI.

**Comment by ttcdt** [comment]
you're right. mp has used traditionally for configuration files and such the value returned by the SHGetSpecialFolderLocation() for CSIDL_PERSONAL, which was somewhat a standard a long ago, but apparently from Windows shell version 5.0 the use of CSIDL_LOCAL_APPDATA is suggested, which seems to point to something like c:\Users\{user}\AppData\Local.

i've changed it for next version.

regards,
theo
