### ISSUE TITLE
How to add syntax highlighting to new language?

### ISSUE THREAD

**Issue by 1e9t8m29** [ttcdt/mp-5.x#26]
I added a new .mpsl on the syntax directory but don't know how to have mp make use of it.

**Comment by ttcdt** [comment]
hi, you have to recompile mp for your file to be used. anyway, we're about to release a new version, so if you publish your file here we'll include it in the next release.

**Comment by 1e9t8m29** [comment]
> hi, you have to recompile mp for your file to be used. anyway, we're about to release a new version, so if you publish your file here we'll include it in the next release.

No, thanks. It's syntax highlighting for the language Umka. It's very incomplete. Not yet cover the full lang specs, just the keywords.
