### ISSUE TITLE
MPSL and New Compilation

### ISSUE THREAD

**Issue by stef204** [ttcdt/mp-5.x#29]
For 5.59 (upgrading from 5.58), `mpsl` is now included in `mp-5.x`?  No need to clone the separate repo `mpsl` any longer? That seems to be behind a login wall, now, anyhow.

If I have the repo `mpsl` cloned previously, do I need to delete that to make sure `mp-5.x` uses the `mpsl` in its own tree?

**Comment by ttcdt** [comment]
yes, `mpsl` is inside MP right now (as well as the other component, `mpdm`). you can delete the `mpsl` repo if you want. you may need to run config.sh again if you have an old version.

**Comment by stef204** [comment]
OK, thanks.
