### ISSUE TITLE
Adding File Type to sh.mpsl

### ISSUE THREAD

**Issue by stef204** [ttcdt/mp-5.x#30]
I'd like to add the filetype (or filename) `PKGBUILD` to the sh.mpsl syntax highlighting file.  So it treats it as a shell script (which it is.)

What is the procedure to do that? And do I need to reconfigure and recompile?

**Comment by ttcdt** [comment]
you can just copy `syntax/bash.mpsl` (or any other 'alias' of the sh syntax highlight) to `syntax/pkgbuild.mpsl` and rebuild MP. reconfiguration is not needed.

**Comment by stef204** [comment]
Nice, that works!
What's going on behind the hood? I see it loads the `sh.mpsl` file.  How does that work in relation to name of the new file one copies, in this case `pkgbuild.mpsl`?

I see this in `syntax.mpsl` :

````
    /* try full name (Makefile, etc.) */
    if (doc.syntax == NULL) {
        if ((v = doc.name->regex("/[^/]+$/"))) {
            doc.syntax = mp.load_syntax(v);
        }
}

````

This is the block responsible for the behavior you described?

What if I want to add yet another syntax highlighting (shell script) for a different kind of file name?  Do you recommend just repeating the above procedure?

Also, is it possible to open a file and only then apply some syntax highlighting using `eval` or some other action?  like: apply syntax highlighting for `shell` (`sh.mpsl`)?
