### ISSUE TITLE
Add the ability to add new syntax highlighting files on the fly

### ISSUE THREAD

**Issue by iahung** [ttcdt/mp-5.x#32]
Without having to rebuild the whole application please. I come from JEdit and it's easily doable.

Let me describe: we already have the mp directory to store settings (mp.mpsl) and data (mp_state.json). Let's create the syntax directory on the mp directory as well and put the user's new syntax highlighting files on it. There should be an option on mp.mpsl file to either automatically make use of the new syntax highlighting files under syntax directory or an option to enable using of them.

This is how JEdit do it. Adding a new mode for a new language on JEdit is effortless.

**Comment by ttcdt** [comment]
a fellow developer tells this:

-------------------------

There is a way to add your own syntax highlight definitions without recompiling. It's not documented AFAIK, but this is how I do it:

1) Add the following line to your `mp.mpsl`:

`push(INC, CONFDIR);`

Previous line adds the CONFDIR (the configuration directory) to the INC array, which holds the subdirectories where code is searched for.

2) Create a subfolder named `syntax` inside your CONFDIR (hit ESC and execute CONFDIR if you don't know the location of the configuration folder).

3) Copy your .mpsl syntax definition and restart the editor.
