### ISSUE TITLE
Default Color - CLI

### ISSUE THREAD

**Issue by stef204** [ttcdt/mp-5.x#34]
Is there a runtime option to change the default font color (when using `mp-5 -txt`) ?
I just cannot read anything against a dark (black) console background.
Or are default colors compile-time option only and if so which file?
(Not syntax highlighting, just basic font color, for example, opening up `mp-5 -txt` and checking `About` or `Update`.)
I tried to change `mp.config.dark_mode` but it does not help.

EDIT:
switching to `branch fixNCursesBackground` fixes this (but that branch is based on `5.58`.)
can the PR for this fix be merged?
https://github.com/ttcdt/mp-5.x/pull/20

**Comment by stef204** [comment]
switching to `branch fixNCursesBackground` fixes this (but that branch is based on `5.58`.
can the PR for this fix be accepted?

**Comment by ttcdt** [comment]
> switching to branch fixNCursesBackground fixes this (but that branch is based on 5.58.) can the PR for this fix be merged?

Hi. I'll take a look at this patch and get back at you on it.

**Comment by ttcdt** [comment]
I've just merged it, it seems to work well.

**Comment by stef204** [comment]
That's great, thanks.
